export const trendingProducts = [
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["COURT STYLE!"],
    price: 39,
    image: "https://i.ibb.co/PjyJtN6/model2.jpg",
    instock: 8,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["OFF SHOULDER!"],
    image: "https://i.ibb.co/BjSZsdB/model1.jpg",
    price: 35,
    instock: 3,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["T-SHIRT VIBE!"],
    image: "https://i.ibb.co/VWPNxsz/model3.jpg",
    price: 39,
    instock: 7,
  },
];

export const typeProducts = [
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jacket",
    image: "https://i.ibb.co/1z2M0M2/jacket1.png",
    price: 15,
    name: ["Jacket1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jacket",
    image: "https://i.ibb.co/H20jP9n/jacket2.png",
    price: 17,
    name: ["Jacket2"],
    instock: 12,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jacket",
    image: "https://i.ibb.co/0nhmzWq/jacket3.png",
    price: 14,
    name: ["Jacket3"],
    instock: 11,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tshirt",
    image: "https://i.ibb.co/bs8fMxq/tshirt1.png",
    price: 15,
    name: ["T-Shirt1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tshirt",
    image: "https://i.ibb.co/16P0VBB/tshirt2.png",
    price: 12,
    name: ["T-Shirt2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tshirt",
    image: "https://i.ibb.co/9GJ8p29/tshirt3.png",
    price: 16,
    name: ["T-Shirt3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tops",
    image: "https://i.ibb.co/LhWSbhk/tops3.png",
    price: 14,
    name: ["Tops1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tops",
    image: "https://i.ibb.co/rb87Nxb/tops2.png",
    price: 16,
    name: ["Tops2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tops",
    image: "https://i.ibb.co/fpvT66k/tops1.png",
    price: 19,
    name: ["Tops3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shirt",
    image: "https://i.ibb.co/qrW0MbC/shirt1.png",
    price: 16,
    name: ["Shirt1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shirt",
    image: "https://i.ibb.co/bQgJc7K/shirt2.png",
    price: 19,
    name: ["Shirt2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shirt",
    image: "https://i.ibb.co/tCjZ8YM/shirt3.png",
    price: 14,
    name: ["Shirt3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "saree",
    image: "https://i.ibb.co/2KcGNB0/saree1.png",
    price: 32,
    name: ["Saree1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "saree",
    image: "https://i.ibb.co/94ZMX61/saree2.png",
    price: 36,
    name: ["Saree2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "saree",
    image: "https://i.ibb.co/6RhcLHX/saree3.png",
    price: 31,
    name: ["Saree3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jens",
    image: "https://i.ibb.co/JxDSKMH/jens1.png",
    price: 15,
    name: ["Jens1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jens",
    image: "https://i.ibb.co/7GF2B8W/jens2.png",
    price: 12,
    name: ["Jens2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jens",
    image: "https://i.ibb.co/5LLsn5W/jens3.png",
    price: 14,
    name: ["Jens3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "blezzer",
    image: "https://i.ibb.co/WsMqbKM/blezzer1.png",
    price: 25,
    name: ["Blezzer1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "blezzer",
    image: "https://i.ibb.co/LkZyxSY/blezzer2.png",
    price: 27,
    name: ["Blezzer1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "blezzer",
    image: "https://i.ibb.co/nc9M97X/blezzer3.png",
    price: 30,
    name: ["Blezzer1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "kids",
    image: "https://i.ibb.co/mytkSbV/kids1.png",
    price: 14,
    name: ["Kids1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "kids",
    image: "https://i.ibb.co/w7X03qM/kids2.png",
    price: 11,
    name: ["Kids2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "kids",
    image: "https://i.ibb.co/0hfvM4w/kids3.png",
    price: 17,
    name: ["Kids3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shorts",
    image: "https://i.ibb.co/0VHxxb8/short1.png",
    price: 14,
    name: ["Shorts1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shorts",
    image: "https://i.ibb.co/dDF9M7p/shorts2.png",
    price: 19,
    name: ["Shorts2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shorts",
    image: "https://i.ibb.co/Yp818zT/shorts3.png",
    price: 22,
    name: ["Short3"],
    instock: 10,
  },
];

export const carouselProducts = [
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/8KPC53n/a.png",
    price: 25,
    instock: 5,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/vqy3YSQ/b.png",
    price: 32,
    instock: 3,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/wz6XwRs/c.png",
    price: 30,
    instock: 5,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/Hrgpzhz/d.png",
    price: 29,
    instock: 4,
  },
];

export const seasonalProducts = [
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/MnjqSVQ/summer1.jpg",
    price: 25,
    name: ["Summer1"],
    instock: 8,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/WfrTz3x/summer2.jpg",
    price: 27,
    name: ["Summer2"],
    instock: 12,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/Qb2kWbz/summer3.jpg",
    price: 22,
    name: ["Summer3"],
    instock: 8,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/XYFv5Nq/summer4.jpg",
    price: 31,
    name: ["Summer4"],
    instock: 5,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/ZxCw2d6/summer5.jpg",
    price: 24,
    name: ["Summer5"],
    instock: 7,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/dBPf1Lc/winter1.jpg",
    price: 39,
    name: ["Winter1"],
    instock: 8,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/P4mXBjc/winter2.jpg",
    price: 49,
    name: ["Winter2"],
    instock: 12,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/qCy3cvz/winter3.jpg",
    price: 33,
    name: ["Winter3"],
    instock: 8,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/F7BFVmC/winter4.jpg",
    price: 39,
    name: ["Winter4"],
    instock: 9,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/fXzBgBF/winter5.jpg",
    price: 34,
    name: ["Winter5"],
    instock: 12,
  },
];

// all products and types name
export const allProducts = [
  {
    offerPrice: 0,
    productId:"season1summer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/MnjqSVQ/summer1.jpg",
    price: 25,
    name: ["Summer1"],
    instock: 8,
  },
  {
    offerPrice: 0,
    productId:"season2summer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/WfrTz3x/summer2.jpg",
    price: 27,
    name: ["Summer2"],
    instock: 12,
  },
  {
    offerPrice: 0,
    productId:"season3summer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/Qb2kWbz/summer3.jpg",
    price: 22,
    name: ["Summer3"],
    instock: 8,
  },
  {
    offerPrice: 0,
    productId:"season4summer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/XYFv5Nq/summer4.jpg",
    price: 31,
    name: ["Summer4"],
    instock: 5,
  },
  {
    offerPrice: 0,
    productId:"season5summer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/ZxCw2d6/summer5.jpg",
    price: 24,
    name: ["Summer5"],
    instock: 7,
  },
  {
    offerPrice: 0,
    productId:"season1winter",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/dBPf1Lc/winter1.jpg",
    price: 39,
    name: ["Winter1"],
    instock: 8,
  },
  {
    offerPrice: 0,
    productId:"season2winter",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/P4mXBjc/winter2.jpg",
    price: 49,
    name: ["Winter2"],
    instock: 12,
  },
  {
    offerPrice: 0,
    productId:"season3winter",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/qCy3cvz/winter3.jpg",
    price: 33,
    name: ["Winter3"],
    instock: 8,
  },
  {
    offerPrice: 0,
    productId:"season4winter",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/F7BFVmC/winter4.jpg",
    price: 39,
    name: ["Winter4"],
    instock: 9,
  },
  {
    offerPrice: 0,
    productId:"season5winter",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "winter",
    image: "https://i.ibb.co/fXzBgBF/winter5.jpg",
    price: 34,
    name: ["Winter5"],
    instock: 12,
  },
  {
    offerPrice: 0,
    productId:"carousel1autumn",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/8KPC53n/a.png",
    price: 25,
    instock: 5,
  },
  {
    offerPrice: 0,
    productId:"carousel2autumn",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/vqy3YSQ/b.png",
    price: 32,
    instock: 3,
  },
  {
    offerPrice: 0,
    productId:"carousel3autumn",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/wz6XwRs/c.png",
    price: 30,
    instock: 5,
  },
  {
    offerPrice: 0,
    productId:"carousel4autumn",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "carousel",
    name: [
      "AUTUMN",
      "COLLECTION",
      "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    ],
    image: "https://i.ibb.co/Hrgpzhz/d.png",
    price: 29,
    instock: 4,
  },
  {
    offerPrice: 0,
    productId:"trending1court",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["COURT STYLE!"],
    price: 39,
    image: "https://i.ibb.co/PjyJtN6/model2.jpg",
    instock: 8,
  },
  {
    offerPrice: 0,
    productId:"trending2court",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["OFF SHOULDER!"],
    image: "https://i.ibb.co/BjSZsdB/model1.jpg",
    price: 35,
    instock: 3,
  },
  {
    offerPrice: 0,
    productId:"trending3court",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["T-SHIRT VIBE!"],
    image: "https://i.ibb.co/VWPNxsz/model3.jpg",
    price: 39,
    instock: 7,
  },
  {
    offerPrice: 0,
    productId:"trending4court",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["FULL COVER VIBE!"],
    image: "https://i.ibb.co/DrLMph9/trending4-1.jpg",
    price: 59,
    instock: 7,
  },
  {
    offerPrice: 0,
    productId:"trending5court",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "trending",
    name: ["JHAKANAKA VIBE!"],
    image: "https://i.ibb.co/MG3ySJ4/trending5-1.jpg",
    price: 25,
    instock: 7,
  },

  {
    offerPrice: 0,
    productId:"type1jacket",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jacket",
    image: "https://i.ibb.co/1z2M0M2/jacket1.png",
    price: 15,
    name: ["Jacket1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2jacket",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jacket",
    image: "https://i.ibb.co/H20jP9n/jacket2.png",
    price: 17,
    name: ["Jacket2"],
    instock: 12,
  },
  {
    offerPrice: 0,
    productId:"type3jacket",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jacket",
    image: "https://i.ibb.co/0nhmzWq/jacket3.png",
    price: 14,
    name: ["Jacket3"],
    instock: 11,
  },
  {
    offerPrice: 0,
    productId:"type1tshirt",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tshirt",
    image: "https://i.ibb.co/bs8fMxq/tshirt1.png",
    price: 15,
    name: ["T-Shirt1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2tshirt",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tshirt",
    image: "https://i.ibb.co/16P0VBB/tshirt2.png",
    price: 12,
    name: ["T-Shirt2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3tshirt",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tshirt",
    image: "https://i.ibb.co/9GJ8p29/tshirt3.png",
    price: 16,
    name: ["T-Shirt3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type1tops",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tops",
    image: "https://i.ibb.co/LhWSbhk/tops3.png",
    price: 14,
    name: ["Tops1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2tops",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tops",
    image: "https://i.ibb.co/rb87Nxb/tops2.png",
    price: 16,
    name: ["Tops2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3tops",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "tops",
    image: "https://i.ibb.co/fpvT66k/tops1.png",
    price: 19,
    name: ["Tops3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type1shirt",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shirt",
    image: "https://i.ibb.co/qrW0MbC/shirt1.png",
    price: 16,
    name: ["Shirt1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2shirt",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shirt",
    image: "https://i.ibb.co/bQgJc7K/shirt2.png",
    price: 19,
    name: ["Shirt2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3shirt",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shirt",
    image: "https://i.ibb.co/tCjZ8YM/shirt3.png",
    price: 14,
    name: ["Shirt3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type1saree",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "saree",
    image: "https://i.ibb.co/2KcGNB0/saree1.png",
    price: 32,
    name: ["Saree1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2saree",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "saree",
    image: "https://i.ibb.co/94ZMX61/saree2.png",
    price: 36,
    name: ["Saree2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3saree",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "saree",
    image: "https://i.ibb.co/6RhcLHX/saree3.png",
    price: 31,
    name: ["Saree3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type1jens",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jens",
    image: "https://i.ibb.co/JxDSKMH/jens1.png",
    price: 15,
    name: ["Jens1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2jens",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jens",
    image: "https://i.ibb.co/7GF2B8W/jens2.png",
    price: 12,
    name: ["Jens2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3jens",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "jens",
    image: "https://i.ibb.co/5LLsn5W/jens3.png",
    price: 14,
    name: ["Jens3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type1blezzer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "blezzer",
    image: "https://i.ibb.co/WsMqbKM/blezzer1.png",
    price: 25,
    name: ["Blezzer1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2blezzer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "blezzer",
    image: "https://i.ibb.co/LkZyxSY/blezzer2.png",
    price: 27,
    name: ["Blezzer1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3blezzer",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "blezzer",
    image: "https://i.ibb.co/nc9M97X/blezzer3.png",
    price: 30,
    name: ["Blezzer1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type1kids",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "kids",
    image: "https://i.ibb.co/mytkSbV/kids1.png",
    price: 14,
    name: ["Kids1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2kids",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "kids",
    image: "https://i.ibb.co/w7X03qM/kids2.png",
    price: 11,
    name: ["Kids2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3kids",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "kids",
    image: "https://i.ibb.co/0hfvM4w/kids3.png",
    price: 17,
    name: ["Kids3"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type1shorts",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shorts",
    image: "https://i.ibb.co/0VHxxb8/short1.png",
    price: 14,
    name: ["Shorts1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type2shorts",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shorts",
    image: "https://i.ibb.co/dDF9M7p/shorts2.png",
    price: 19,
    name: ["Shorts2"],
    instock: 10,
  },
  {
    offerPrice: 0,
    productId:"type3shorts",
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "shorts",
    image: "https://i.ibb.co/Yp818zT/shorts3.png",
    price: 22,
    name: ["Short3"],
    instock: 10,
  },
];

export const cartProducts = [
  {
    type: "jacket",
    image: "https://i.ibb.co/1z2M0M2/jacket1.png",
    price: 15,
    name: ["Jacket1"],
    instock: 10,
  },
  {
    offerPrice: 0,
    color: ["Gray", "Black", "Pink", "Blue"],
    size: ["M", "L", "XL", "XXL"],
    type: "summer",
    image: "https://i.ibb.co/MnjqSVQ/summer1.jpg",
    price: 25,
    name: ["Summer1"],
    instock: 8,
  },
];

export const typesName = [
  {
    name: "Jacket",
    type: "jacket",
    image: "https://i.ibb.co/0Kkch7Y/jacket-removebg-preview.png",
  },

  {
    name: "Jens",
    type: "jens",
    image: "https://i.ibb.co/ZxTtf4K/jens-removebg-preview.png",
  },
  {
    name: "Blezzer",
    type: "blezzer",
    image: "https://i.ibb.co/wLmLCLR/blezzer-removebg-preview.png",
  },

  {
    name: "Shirt",
    type: "shirt",
    image: "https://i.ibb.co/NrtNHLZ/shirt-removebg-preview.png",
  },

  {
    name: "Tops",
    type: "tops",
    image: "https://i.ibb.co/fG7VqWR/tops-removebg-preview.png",
  },
  {
    name: "T-Shirt",
    type: "tshirt",
    image: "https://i.ibb.co/1QbgJ5L/tshirt.png",
  },

  {
    name: "Saree",
    type: "saree",
    image: "https://i.ibb.co/8XbQFTs/sarre-removebg-preview.png",
  },
  {
    name: "Kids",
    type: "kids",
    image: "https://i.ibb.co/VvxCgGZ/kids.png",
  },
  {
    name: "Shorts",
    type: "shorts",
    image: "https://i.ibb.co/7XsDLZQ/shorts.png",
  },
];
